# Generated by Django 5.2.17 on 2026-08-13 07:48

from django.db import migrations

def seed_roles(apps, schema_editor):
    Role = apps.get_model('api', 'Role')
    roles = ['Admin', 'Student', 'Teacher']
    for name in roles:
        Role.objects.get_or_create(role_name=name)

def remove_roles(apps, schema_editor):
    Role = apps.get_model('api', 'Role')
    Role.objects.filter(role_name__in=['Admin', 'Student', 'Teacher']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_roles, remove_roles),
    ]
