# Generated by Django 5.2.17 on 2026-08-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='class_teacher_of',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
